apiVersion: batch/v1
kind: Job
metadata:
  name: storplan-build-backend
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - "--context=git://github.com/wutz/storplan.git"
        - "--dockerfile=Dockerfile.backend"
        - "--destination=cr.dev1.bz1.paratera.com/library/storplan-backend:latest"
        - "--insecure"
        - "--skip-tls-verify"
      restartPolicy: Never
  backoffLimit: 1
---
apiVersion: batch/v1
kind: Job
metadata:
  name: storplan-build-frontend
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - "--context=git://github.com/wutz/storplan.git"
        - "--dockerfile=Dockerfile.frontend"
        - "--destination=cr.dev1.bz1.paratera.com/library/storplan-frontend:latest"
        - "--insecure"
        - "--skip-tls-verify"
      restartPolicy: Never
  backoffLimit: 1
